### ISSUE TITLE
nosnap: allow -> Event dropped - No snapshot or clip available

### ISSUE THREAD

**Issue by d4rkw1n9** [0x2142/frigate-notify#130]
Hello

I am experiencing a strange issue with regards to the sending of alerts even if no snapshot is available. The relevant portion of the frigate-notify config is as follows:

```
## Alerting methods
# Any combination of alert destinations can be configured
alerts:  
  # General config applies to all alert methods below
  general:
    # Title for any alert messages (Default: Frigate Alert)
    title: Surveillance Alert
    # Optionally modify default time format in notifications
    # Use Golang's reference time format, or see docs for more info
    timeformat:
    # Allow notification of events without a snapshot
    # Set to `drop` to disallow this
    nosnap: allow
    # Note: Following snap_ items only apply when event is in progress
    # Set to `true` to include bounding box on detected object in snapshot
    snap_bbox:
    # Set to `true` to include timestamp on snapshot
    snap_timestamp:
    # Set to `true` to crop snapshot
    snap_crop:
````

Although nosnap is set to allow, I still get no alerts with the following log entry:

`2024/09/06 17:52:40 +0200 INF New event received event_id=1725637954.289952-d8qyed
2024/09/06 17:52:40 +0200 INF Event Detected camera=tapo_cam_c320 event_id=1725637954.289952-d8qyed label=person zones=
2024/09/06 17:52:40 +0200 INF Event dropped - No snapshot or clip available event_id=1725637954.289952-d8qyed
2024/09/06 17:52:41 +0200 INF Event update received event_id=1725637954.289952-d8qyed
2024/09/06 17:52:41 +0200 INF Event Detected camera=tapo_cam_c320 event_id=1725637954.289952-d8qyed label=person zones=
2024/09/06 17:52:41 +0200 INF Event dropped - Already notified on this zone camera=tapo_cam_c320 event_id=1725637954.289952-d8qyed label=person zones=`

Any ideas on how to fix this? Maybe configuration error or even a bug? 

Thanks a lot - great project!

**Comment by 0x2142** [comment]
Hi there! So at the moment there is one circumstance where this might happen - if there is no snapshot **and** no clip available via Frigate. This was originally implemented because some users have certain filtering configured on the Frigate side, like setting `required_zones` on a camera. This would result in Frigate still generating an event, but not recording anything yet - which would still trigger a notification via this app. The config setting is mostly there to change notification preference on snapshot availability only. 

Now assuming that the detected object eventually enters a spot where there should be a clip recorded, you should be notified. However, there is an open issue (#121) where that isn't always the case.

**Comment by d4rkw1n9** [comment]
> Hi there! So at the moment there is one circumstance where this might happen - if there is no snapshot **and** no clip available via Frigate. This was originally implemented because some users have certain filtering configured on the Frigate side, like setting `required_zones` on a camera. This would result in Frigate still generating an event, but not recording anything yet - which would still trigger a notification via this app. The config setting is mostly there to change notification preference on snapshot availability only.
> 
> Now assuming that the detected object eventually enters a spot where there should be a clip recorded, you should be notified. However, there is an open issue (#121) where that isn't always the case.

Thanks a lot for the quick and extensive reply. Will head over to issue #121 and close this one here.
