### ISSUE TITLE
SMTP without TLS doesn't work

### ISSUE THREAD

**Issue by undefinedid** [0x2142/frigate-notify#16]
Hi Matt,

Thank you for developing such application! It fills a gap which allows you to avoid having to run a mqtt broker!

I'm trying to use the SMTP alerts but I think there is a problem.
My SMTP relay is in my LAN, and does not need to authenticate or the use of TLS/SSL to send emails.

So, when  `frigate-notify` is about to sends the alert, it gives me this error even if I specified the TLS option in the Yaml:

```
2023/11/29 19:24:46 Checking for new events...
2023/11/29 19:24:46 Found 1 new events.
2023/11/29 19:24:46 Event ID 1701282275.839471-y31jy3 detected person in zone(s): []
2023/11/29 19:24:46 Event Start time:  2023-11-29 19:24:33 +0100 CET
2023/11/29 19:24:51 Failed to send SMTP message: dial failed: STARTTLS mode set to: "TLSMandatory", but target host does not support STARTTLS
2023/11/29 19:24:51 SMTP alert sent
2023/11/29 19:25:21 Checking for new events...
```

Here is the alert section of my config file:

```
alerts:  
  general:
    title: "Frigate_Alert"
    
  smtp:
    enabled: true
    server: 192.168.0.254
    port: 25
    tls: false
    user:
    password:
    recipient: xxx@yyy.zzz,aaa@bbb.ccc
 ```
 
Do you have any idea where the problem could come from?

I saw the import of the variable in [smtp.go#L17](https://github.com/0x2142/frigate-notify/blob/main/notifier/smtp.go#L17), but I'm not sure it is reused in the `SendSMTP` function.

Many thanks for your help!

**Comment by 0x2142** [comment]
Hi there! Thanks so much for using this app! 

I took a quick look & can replicate your issue. I must never have tested this, since I have my instance set to use Gmail's SMTP relay. I do have a local unauthenticated relay on my LAN - where I can see the same issue occuring

As it turns out, the module I'm using for SMTP has mandatory TLS enabled by default. So it must have just slipped by that I wasn't using the `SMTPTLS` variable.

Should be a quick fix though & I can push out a new version once it's resolved!

**Comment by 0x2142** [comment]
Hi there - Just a quick update. I released a new version that contains fixes for your issue. There is an updated docker image [here](https://github.com/0x2142/frigate-notify/pkgs/container/frigate-notify/152895788?tag=v0.2.2). I am running into an issue at the moment getting the binaries built - but I hope to look at that some more tomorrow.
