### ISSUE TITLE
Crashing after mqtt event received

### ISSUE THREAD

**Issue by monogoat** [0x2142/frigate-notify#24]
Testing this out, I'm having an issue where the docker crashes when sending the notification to gotify I think. Here is the log:

2024/03/13 21:46:37 Event ID 1710380793.366356-hjwenm on camera driveway1 detected person in zone(s): []
2024/03/13 21:46:37 Event Start time:  2024-03-13 21:46:33 -0400 EDT
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4976b5]

goroutine 19 [running]:
io.ReadAll({0x0, 0x0})
        /usr/local/go/src/io/io.go:704 +0x55
github.com/0x2142/frigate-notify/notifier.SendAlert({0xc0002c4080, 0x74}, {0x0, 0x0}, {0x0?, 0x0?})
        /app/notifier/alerts.go:16 +0x3b
github.com/0x2142/frigate-notify/events.processEvent({0x0?, 0x0?}, {0x850fd0, 0xc000198050})
        /app/events/mqtt.go:96 +0x54a
github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch.func2()
        /go/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.4.3/router.go:218 +0x930
created by github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch in goroutine 6
        /go/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.4.3/router.go:173 +0x21c

Here is the config file:

frigate:
  server: 10.1.0.10:5000
  ignoressl: false

  webapi:
    enabled: false
    interval: 30

  mqtt:
    enabled: true
    server: 10.1.0.10
    port: 1883
    clientid:
    username: REDACTED
    password: REDACTED

  cameras:
    exclude:
      - breakroom
      - office
      - reception

alerts:
  general:
    title: Test

  gotify:
    enabled: true
    server: 10.0.0.10:8070
    token: REDACTED
    ignoressl: false

monitor:
  enabled: false
  url:
  interval:
  ignoressl:

**Comment by 0x2142** [comment]
Hi there - 
  Thanks for using this project! I appreciate you testing & providing logs and config samples - that helps me a lot!

Based on what I'm seeing, I think that it's crashing because there isn't a snapshot available with the Frigate event when we try to retrieve it. So I need to update the code to still send a message if there is no snapshot - which I thought I had already accounted for, but admittedly I've not yet run into this yet.

Additionally, I am wondering if we might have run into this because your Frigate instance took a while to generate the snapshot? If that's the case, I can try to build in a retry to wait a few moments & check again for a snapshot.

Could you please check the event info for me? Using the info you provided, the event info would be available at `http://10.1.0.10:5000/api/events/1710380793.366356-hjwenm` & the snapshot for that event would be at `http://10.1.0.10:5000/api/events/1710380793.366356-hjwenm/snapshot.jpg`. Of course, you may need to update the IP, port, and event ID in those URLs to match your setup if the info you provided was sanitized.

If you try the snapshot URL, does the image load? And from the event info, could you share the values from `start_time`, `end_time`, and `has_snapshot`? 

Thanks!

**Comment by monogoat** [comment]
That is giving me and event not found, and {"message":"Event not found","success":false}. Since this event is not showing a zone, it makes sense that it does not have an event or snapshot as Frigate is configured only to make events for cars in zones. I ran into this with Home Assistant, Frigate sends out mqtt for everything regardless of how the events are set up.

**Comment by 0x2142** [comment]
Ahh okay, that helps. I haven't configured any zones on my Frigate server yet. So assuming in this case, since you're restricting events only to within specified zones - then you are looking to receive notifications only a detection is triggered in a zone? 

Just want to double check that I understand what the desired outcome is. I'll have to set up a test camera with zones & figure out how I want to approach that - but it should be doable.

**Comment by monogoat** [comment]
Yes that is the plan. My cameras face a busy road, so I have zones set in the driveway.

**Comment by 0x2142** [comment]
Got it. Thanks a lot! I can fix the crash, then I think I'll probably add a config option to ignore events without a zone.

With any luck, I should have time in the next day or two - but I'll keep you updated.

**Comment by 0x2142** [comment]
Okay, I just pushed a new release with a config file section for zone-based alerting. The docs have info on the settings & how to use them: https://frigate-notify.0x2142.com/config/#zones

Let me know if that helps!

**Comment by monogoat** [comment]
That solved the crash, thanks
