### ISSUE TITLE
Documentation of server address is incomplete

### ISSUE THREAD

**Issue by mike2307** [0x2142/frigate-notify#56]
The documentation states that the frigate server property should get assigned the "IP or hostname of the Frigate NVR".

In reality this should be a URL.
In my case the value, which works and doesn't throw any warnings, is http://frigate-host:5000

Therefore the documentation should be extended.
Further, it may be a good idea to use frigate's default port 5000 in case no port number was provided in the URL.

**Comment by 0x2142** [comment]
Hm, can you share what config you used that did create a warning or error? 

Currently this should accept any IP or URL - and if you don't include `http://` or `https://`, then the code automatically will prepend `http://`. So even if I enter `10.10.10.10`, the app will connect to `http://10.10.10.10`

I don't have a default port set since I have Frigate behind a reverse proxy - so in my case, it's at `https://nvr.some-domain.local` - which would be port `443`. If I set a default of `5000`, then anyone who used a reverse proxy would need to override the port in their URL - like in this example `https://nvr.some-domain.local:443` which might be more confusing. However, I'm okay with updating the documentation to note the port requirement if you're pointing this directly at Frigate.
